--- # Favorite movies, conventional  block format uses a dash to begin a new item in list 
- North by Northwest
-
	- Jane Jones
	- 44

Casablanca :
	- Jane Doe
	- 77
Notorious : 
	name: John Doe
	age: 66

--- # Block
name: John Smith
age: 33

--- # Shopping list, optional inline format is delimited by comma+space and enclosed in brackets.
[milk, pumpkin pie, eggs, juice]

--- # Inline
{color: "Lemon yellow", size: 100}
